### ISSUE TITLE
mikeh zsh theme doesn't match the screenshot on wiki

### ISSUE THREAD

**Issue by amateomi** [ohmyzsh/wiki#22]
### Describe the bug

Screenshot of mikeh theme is outdated.
 ![mikeh theme](https://user-images.githubusercontent.com/49100982/108254900-93805580-716c-11eb-9e39-5e8dda6c2308.jpg)
Now it is looks completely different.

### Steps to reproduce

1. Set ZSH_THEME="mikeh" in ~/.zshrc

### Expected behavior

The theme does not match the example in the screenshot.

### Screenshots and recordings

The theme looks like this:
![image](https://user-images.githubusercontent.com/74430714/177345339-f7fb0f41-00ef-430e-a431-99bcad32d026.png)

### OS / Linux distribution

Fedora 36

### Zsh version

5.8.1

### Oh My Zsh version

master (4c82a2e)

### Terminal emulator

Alacritty

**Comment by mcornella** [comment]
@robbyrussell can you take care of regenerating the screenshot for the `mikeh` theme? It should be enough to set the same [defaults as in the generator README](https://github.com/Kovah/oh-my-zsh-screenshot-generation/tree/main#setup) and taking a single capture for the theme (no need to run the Automator app). You can then post the screenshot in a comment in this issue and I'll add it to the page.

BTW I'm asking you directly because neither Carlo nor me have a macOS handy. Thanks!

**Comment by robbyrussell** [comment]
@mcornella does this do the trick for you?



![Image](https://github.com/ohmyzsh/wiki/assets/257/75b979d3-d959-4bab-8990-6de7ff77520b)

**Comment by carlosala** [comment]
Updated, thanks Robby!
